name: authentication_repository
description: Dart package which manages authentication for STLK
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.0+1
  google_sign_in: ^4.5.9
  meta: ^1.2.4
