name: messaging_repository
description: Dart package to manage Firebase Cloud Messaging for STLK
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3