name: messaging_repository
description: Dart package to manage Firebase Cloud Messaging for STLK
version: 1.0.0

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  flutter_local_notifications: ^4.0.0
