name: api_repository
description: Dart package that manages HTTP API calls for STLK
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  equatable: ^1.2.5
  http: ^0.12.2